
public class Config {

    public static final String SUCCESSFUL_PARSE_MESSAGE = "<<<<<< Successful parse >>>>>>";
    public static final String UN_SUCCESSFUL_PARSE_MESSAGE = "<<<<<< UN-successful parse >>>>>>";
    public static final String SUCCESSFUL_COMPILE_MESSAGE = "<<<<<< Successful Compile >>>>>>";
    public static final String UN_SUCCESSFUL_COMPILE_MESSAGE = "<<<<<< UN-successful Compile >>>>>>";
    public static final String TIGER_PROGRAM_GENERATED_IR_CODE_MESSAGE = "Generated IR Code";
    public static final String TIGER_PARSER_SEQUENCE_TOKEN_TYPES_OUTPUT_MESSAGE = "Tiger Parser Sequence Token Types Output";
    public static final String PARSER_SEQUENCE_TOKEN_TYPES_MESSAGE = "Parser Sequence Token types";
    public static final String TIGER_PARSE_TREE_OUTPUT_MESSAGE = "Tiger ParseTree Output";
    public static final String SYMBOL_TABLE_REPRESENTATION = "Program Symbol Table";
    public static final String PRINTS_FUNCTION_NAME = "prints";
    public static final String PRINTI_FUNCTION_NAME = "printi";
    public static final String FLUSH_FUNCTION_NAME = "flush";
    public static final String GETCHAR_FUNCTION_NAME = "getchar";
    public static final String STRING_KEYWORD = "string";
    public static final String SCOPE = "Scope";
    public static final String ROOT = "root";
    public static final String VOID = "void";
    public static final String NEW_LINE = "\n";
    public static final String NEW_TAB = "\t";
    public static final String OPEN_TUPLE = "<";
    public static final String CLOSED_TUPLE = ">";
    public static final String SPACE = " ";
    public static final String COMMA = ",";
    public static final String COLON = ":";
    public static final String DOT = ".";
    public static final String EMPTY_STRING = "";
    public static final String ASSIGN = ":=";
    public static final String INT = "int";
    public static final String FLOAT = "float";
    public static final String OPEN_BRACKET = "[";
    public static final String CLOSED_BRACKET = "]";
    public static final String ARRAY_KEYWORD = "array";
    public static final String TYPE_KEYWORD = "type";
    public static final String FUNC_KEYWORD = "func";
    public static final String VAR_KEYWORD = "var";
    public static final String WHILE_KEYWORD = "while";
    public static final String FOR_KEYWORD = "for";
    public static final String IF_KEYWORD = "if";
    public static final String BREAK_KEYWORD = "break";
    public static final String RETURN_KEYWORD = "return";
    public static final String MAIN_KEYWORD = "main";
    public static final String LET_KEYWORD = "let";
    public static final String LOOP_LABEL = "loop_label";
    public static final String WHILE_LABEL = "while_label";
    public static final String IF_LABEL = "if_after_label";
    public static final String OP_BRANCH_breq = "breq";
    public static final String OP_BRANCH_brneq = "brneq";
    public static final String OP_BRANCH_brlt = "brlt";
    public static final String OP_BRANCH_brgt = "brgt";
    public static final String OP_BRANCH_brleq = "brleq";
    public static final String OP_BRANCH_brgeq = "brgeq";
    public static final String OP_BRANCH_GOTO_LABEL_COLON = ":";
    public static final String OP_ADD = "add";
    public static final String OP_SUB = "sub";
    public static final String OP_GOTO = "goto";
    public static final String OP_OR = "or";
    public static final String OP_AND = "and";
    public static final String OP_MULTIPLICATION = "mul";
    public static final String OP_DIVISION = "div";
    public static final String OP_POWER = "pow";
    public static final String OP_RETURN = "return";
    public static final String OP_CALL = "call";
    public static final String SIGN_POWER = "**";
    public static final String SIGN_MULTIPLICATION = "*";
    public static final String SIGN_DIVISION = "/";
    public static final String SIGN_ADD = "+";
    public static final String SIGN_SUB = "-";
    public static final String SIGN_OR = "|";
    public static final String SIGN_EQ = "==";
    public static final String SIGN_NEQ = "!=";
    public static final String SIGN_LESSER = "<";
    public static final String SIGN_GREATER = ">";
    public static final String SIGN_LESSEREQ = "<=";
    public static final String SIGN_GREATEREQ = ">=";
    public static final String REGISTER_NAME = "$t";
    public static final String ONE = "1";
    public static final String IN_LINE = ", in line: ";
    public static final String OF_PROGRAM = ", of your program: ";
    public static final String SYMBOL_TABLE_GENERATION_ERROR_MESSAGE = "Cannot create Symbol-Table due to Compile/Runtime Error/Problem in your program, ";
    public static final String VARIABLE_NOT_DEFINED_ERROR = "is not defined for its current 'scope' in your Tiger program";
    public static final String TIGER_RUNTIME_EXCEPTION = "Tiger Compile Un-successful. Tiger Runtime Exception in your Tiger program during your";
    public static final String TIGER_COMPILE_UNSUCCESSFUL = "Tiger Compile Un-successful";

}

